export const FETCH_POLLS_REQUEST = 'FETCH_POLLS_REQUEST';
export const FETCH_POLLS_SUCCESS = 'FETCH_POLLS_SUCCESS';
export const FETCH_POLLS_FAILURE = 'FETCH_POLLS_FAILURE';

export const FETCH_RESULT_REQUEST = 'FETCH_RESULT_REQUEST';
export const FETCH_RESULT_SUCCESS = 'FETCH_RESULT_SUCCESS';
export const FETCH_RESULT_FAILURE = 'FETCH_RESULT_FAILURE';